export default data = [
    {
      id: 1,
      title: 'Coat',
      imgurl: require('../assets/images/Mask6.png'),
      type: 'product',
    },
    {
      id: 2,
      title: 'Hoodie',
      imgurl: require('../assets/images/Mask5.png'),
      type: 'product',
    },
    {
      id: 3,
      title: 'Shirt',
      imgurl: require('../assets/images/Mask7.png'),
      type: 'product',
    },
    {
      id: 4,
      title: 'Coat',
      imgurl: require('../assets/images/Mask6.png'),
      type: 'product',
    },
    {
      id: 5,
      title: 'Hoodie',
      imgurl: require('../assets/images/Mask5.png'),
      type: 'product',
    },
    {
      id: 6,
      title: 'Shirt',
      imgurl: require('../assets/images/Mask7.png'),
      type: 'product',
    },
    {
      id: 7,
      title: 'Coat',
      imgurl: require('../assets/images/Mask6.png'),
      type: 'product',
    },
    {
      id: 8,
      title: 'Hoodie',
      imgurl: require('../assets/images/Mask5.png'),
      type: 'product',
    },
    {
      id: 9,
      title: 'Shirt',
      imgurl: require('../assets/images/Mask7.png'),
      type: 'product',
    },
    {
      id: 10,
      title: 'Coat',
      imgurl: require('../assets/images/Mask6.png'),
      type: 'product',
    },
    {
      id: 11,
      title: 'Hoodie',
      imgurl: require('../assets/images/Mask5.png'),
      type: 'product',
    },
    {
      id: 12,
      title: 'Shirt',
      imgurl: require('../assets/images/Mask7.png'),
      type: 'product',
    },
    {
      id: 13,
      title: 'Coat',
      imgurl: require('../assets/images/Mask6.png'),
      type: 'product',
    },
    {
      id: 14,
      title: 'Hoodie',
      imgurl: require('../assets/images/Mask5.png'),
      type: 'product',
    },
    {
      id: 15,
      title: 'Shirt',
      imgurl: require('../assets/images/Mask7.png'),
      type: 'product',
    },
    {
      id: 16,
      title: 'Coat',
      imgurl: require('../assets/images/Mask6.png'),
      type: 'product',
    },
    {
      id: 17,
      title: 'Hoodie',
      imgurl: require('../assets/images/Mask5.png'),
      type: 'product',
    },
    {
      id: 18,
      title: 'Shirt',
      imgurl: require('../assets/images/Mask7.png'),
      type: 'product',
    },
  ];